<?php
$installer = $this;
$installer->startSetup();

$installer->addAttribute('catalog_product', 'borderfree_restricted',  array(
		'group' => 'Borderfree',
		'sort_order' => 1,
		'type' => 'int',
		'backend' => '',
		'frontend' => '',
		'label' => 'Borderfree Restricted',
		'note' => 'This product will be restricted from the Borderfree catalog.',
		'input' => 'select',
		'class' => '',
		'source' => 'eav/entity_attribute_source_boolean',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_WEBSITE,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '0',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false
));

$installer->addAttribute('catalog_product', 'gtin',  array(
		'group' => 'Borderfree',
		'sort_order' => 10,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Global Trade Item Number',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'upc',  array(
		'group' => 'Borderfree',
		'sort_order' => 11,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Universal Product Code',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'ean',  array(
		'group' => 'Borderfree',
		'sort_order' => 12,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'European Article Number',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'apn',  array(
		'group' => 'Borderfree',
		'sort_order' => 13,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Australian Product Number',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'jan',  array(
		'group' => 'Borderfree',
		'sort_order' => 14,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Japanese Article Number',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'eccn',  array(
		'group' => 'Borderfree',
		'sort_order' => 15,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Export Control Classification Number',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'mpn',  array(
		'group' => 'Borderfree',
		'sort_order' => 16,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Manufacturer Part Number',
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => 'simple',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'manufacturer',  array(
		'group' => 'Borderfree',
		'sort_order' => 4,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Manufacturer',
		'note' => '',
		'input' => 'select',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => true,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => true,
		'apply_to' => '',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => true,
		'visible_in_advanced_search' => true,
		'used_for_price_rules' => true,
		'filterable_in_search' => true
));

$installer->addAttribute('catalog_product', 'brand',  array(
		'group' => 'Borderfree',
		'sort_order' => 5,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Brand',
		'note' => '',
		'input' => 'select',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => true,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => true,
		'apply_to' => '',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => true,
		'visible_in_advanced_search' => true,
		'used_for_price_rules' => true,
		'filterable_in_search' => true
));

$installer->addAttribute('catalog_product', 'collection',  array(
		'group' => 'Borderfree',
		'sort_order' => 6,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Collection',
		'note' => '',
		'input' => 'select',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => true,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => true,
		'apply_to' => '',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => true,
		'visible_in_advanced_search' => true,
		'used_for_price_rules' => true,
		'filterable_in_search' => true
));

$installer->addAttribute('catalog_product', 'gender',  array(
		'group' => 'Borderfree',
		'sort_order' => 7,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Gender',
		'note' => '',
		'input' => 'select',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => true,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => true,
		'apply_to' => '',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => true,
		'visible_in_advanced_search' => true,
		'used_for_price_rules' => true,
		'filterable_in_search' => true
));

$installer->addAttribute('catalog_product', 'age',  array(
		'group' => 'Borderfree',
		'sort_order' => 8,
		'type' => 'varchar',
		'backend' => 'eav/entity_attribute_backend_array',
		'frontend' => '',
		'label' => 'Age',
		'note' => '',
		'input' => 'multiselect',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => true,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => true,
		'apply_to' => '',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => true,
		'visible_in_advanced_search' => true,
		'used_for_price_rules' => true,
		'filterable_in_search' => true
));

$installer->addAttribute('catalog_product', 'season',  array(
		'group' => 'Borderfree',
		'sort_order' => 9,
		'type' => 'varchar',
		'backend' => 'eav/entity_attribute_backend_array',
		'frontend' => '',
		'label' => 'Season',
		'note' => '',
		'input' => 'multiselect',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => true,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => true,
		'apply_to' => '',
		'searchable' => true,
		'filterable' => 1,
		'comparable' => true,
		'visible_in_advanced_search' => true,
		'used_for_price_rules' => true,
		'filterable_in_search' => true
));

$installer->addAttribute('catalog_product', 'is_exclusive',  array(
		'group' => 'Borderfree',
		'sort_order' => 3,
		'type' => 'int',
		'backend' => '',
		'frontend' => '',
		'label' => 'Is Exclusive',
		'note' => 'Indicates whether the Product is exclusive to your catalog.',
		'input' => 'select',
		'class' => '',
		'source' => 'eav/entity_attribute_source_boolean',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '0',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false
));

$installer->addAttribute('catalog_product', 'hs_codes',  array(
		'group' => 'Borderfree',
		'sort_order' => 19,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => 'Harmonized System (HS) codes',
		'note' => 'Comma Separated List',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => '',
		'searchable' => false,
		'filterable' => 0,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));

$installer->addAttribute('catalog_product', 'is_ormd',  array(
		'group' => 'Borderfree',
		'sort_order' => 20,
		'type' => 'int',
		'backend' => '',
		'frontend' => '',
		'label' => 'Is ORM-D',
		'note' => 'Indicates if the SKU has the "Other Regulated Materials for Domestic transport only"',
		'input' => 'select',
		'class' => '',
		'source' => 'eav/entity_attribute_source_boolean',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '0',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false
));

$installer->addAttribute('catalog_product', 'is_fws_permit_req',  array(
		'group' => 'Borderfree',
		'sort_order' => 21,
		'type' => 'int',
		'backend' => '',
		'frontend' => '',
		'label' => 'Fish and Wildlife Services permit required',
		'note' => '',
		'input' => 'select',
		'class' => '',
		'source' => 'eav/entity_attribute_source_boolean',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '0',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false
));

$installer->addAttribute('catalog_product', 'fws_permit_details',  array(
		'group' => 'Borderfree',
		'sort_order' => 22,
		'type' => 'varchar',
		'backend' => '',
		'frontend' => '',
		'label' => "Item's description for the FWS permit",
		'note' => '',
		'input' => 'text',
		'class' => '',
		'source' => '',
		'global' => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
		'visible' => true,
		'required' => false,
		'user_defined' => true,
		'default' => '',
		'visible_on_front' => false,
		'unique' => false,
		'is_configurable' => false,
		'used_for_promo_rules' => false,
		'apply_to' => '',
		'searchable' => false,
		'filterable' => 0,
		'comparable' => false,
		'visible_in_advanced_search' => false,
		'used_for_price_rules' => false,
		'filterable_in_search' => false
));


$installer->endSetup();
?>
